### ISSUE TITLE
Change tagline and docs theme

### ISSUE THREAD

**Issue by jaredpalmer** [andycall/RCRE#8]
Please change your docs theme, structure, and tagline. Thanks!

https://twitter.com/jaredpalmer/status/1128750884417101825?s=20

**Comment by andycall** [comment]
I did refer to the theme of formik and tagline, I'm sorry for that.

But this is my personal project, there are no relations between RCRE and Baidu.inc. If you have any questions, please just @ my [twitter account](https://twitter.com/HelloAndyCall)

By the way, formik is an open source project under MIT license, I understand that everything in this project can be borrowed, including themes and taglines.

I use this tagline just because RCRE and formik have similar goals -- making some complicated things easier. As for theme, it's just a color similar to bootstrap.

In addition to themes and tagline, RCRE and formik are two completely different projects, including code, design, documentation, and more.

If you don't feel comfortable of this, I will change it later.

Formik is an excellent project, It give me more inspirations of the working of RCRE.

Thanks.

**Comment by andycall** [comment]
docs theme and tagline has been changed

**Comment by jaredpalmer** [comment]
Thanks Andy. I appreciate the follow up.
